// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/13/2025, 2:50:00 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/Project/PawnShop/Host/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/PawnShop/Host/website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/PawnShop/Host/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/PawnShop/Host/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/PawnShop/Host/website/plugins/**/*.{js,ts,mjs}","D:/Project/PawnShop/Host/website/composables/**/*.{js,ts,mjs}","D:/Project/PawnShop/Host/website/utils/**/*.{js,ts,mjs}","D:/Project/PawnShop/Host/website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/PawnShop/Host/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Project/PawnShop/Host/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Project/PawnShop/Host/website/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;